# Generated by Django 5.2.1 on 2025-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_repairshop_options_alter_repairshop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='closing_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='max_daily_appointments',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
